version: "2"
services:
  guacamole:
    image: oznu/guacamole:latest
    container_name: honeybee-guacamole
    volumes:
      - .:/config
    ports:
      - 8080:8080
volumes:
  postgres:
    driver: local