version: "2"
services:
  guacamole:
    image: oznu/guacamole:latest
    container_name: guacamole
    volumes:
      - postgres:/config
    ports:
      - 8080:8080
volumes:
  postgres:
    driver: local